name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Install dependencies
    - run: composer install
    - name: Copy .env
    - run: php -r "file_exists('.env') || copy('.env.production', '.env');"
    - run: php artisan config:cache
    - run: php artisan route:cache
    
    env:
      APP_KEY: ${{ secrets.APP_KEY }}